/** Tarifas orientativas de mercado (País Vasco, 2025) como respaldo si el negocio no tiene tabla propia. */
export const TARIFAS_BASE_ALBANILERIA = [
  { nombre: 'Demolición/picado de paredes', unidad: 'm2', precio: 18, categoria: 'demolicion' },
  { nombre: 'Demolición/picado de suelo', unidad: 'm2', precio: 15, categoria: 'demolicion' },
  { nombre: 'Retirada de escombros', unidad: 'm3', precio: 90, categoria: 'demolicion' },
  { nombre: 'Tabique de ladrillo', unidad: 'm2', precio: 52, categoria: 'tabique' },
  { nombre: 'Alicatado de azulejo', unidad: 'm2', precio: 35, categoria: 'alicatado' },
  { nombre: 'Solado de gres/cerámica', unidad: 'm2', precio: 38, categoria: 'suelo' },
  { nombre: 'Solera de hormigón', unidad: 'm2', precio: 32, categoria: 'suelo' },
  { nombre: 'Enfoscado de cemento', unidad: 'm2', precio: 22, categoria: 'enfoscado' },
  { nombre: 'Nivelación del suelo con mortero', unidad: 'm2', precio: 18, categoria: 'suelo' },
  { nombre: 'Pintura interior', unidad: 'm2', precio: 10, categoria: 'pintura' },
  { nombre: 'Pintura exterior', unidad: 'm2', precio: 14, categoria: 'pintura' },
  { nombre: 'Falso techo de pladur', unidad: 'm2', precio: 48, categoria: 'techo' },
  { nombre: 'Impermeabilización', unidad: 'm2', precio: 28, categoria: 'impermeabilizacion' },
  { nombre: 'Fontanería básica', unidad: 'ud', precio: 140, categoria: 'fontaneria' },
  { nombre: 'Instalación sanitarios', unidad: 'ud', precio: 180, categoria: 'fontaneria' },
  { nombre: 'Instalación eléctrica básica', unidad: 'ud', precio: 160, categoria: 'electricidad' },
  { nombre: 'Mano de obra general', unidad: 'hora', precio: 28, categoria: 'mano_obra' },
  { nombre: 'Oficial primera albañilería', unidad: 'hora', precio: 32, categoria: 'mano_obra' },
  { nombre: 'Reforma completa de baño', unidad: 'm2', precio: 420, categoria: 'reforma' },
  { nombre: 'Reforma completa de cocina', unidad: 'm2', precio: 380, categoria: 'reforma' },
] as const;
